version: '3.7'

services:
  db:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    env_file: 
      - ./.env
    volumes:
        - db_data:/var/lib/mysql #persistent data

  api:
    container_name: chat-back
    build: ./api
    command: npm run start:cache
    restart: always
    env_file: 
      - ./.env
    environment: 
      - DATABASE_HOST=db
      - PORT=4000
      - WS_PORT=4001
    depends_on: 
      - db
    ports:
      - '3000:3000'
      - '4000:4000'
      - '4001:4001'
      - '35729:35729'
    volumes:
      - ./api:/var/build
      - /var/build/node_modules

  client:
    container_name: chat-front
    build: ./client
    command:  npm start
    restart: always
    tty: true
    environment: 
      - API=api
    network_mode: service:api
    volumes:
      - './client:/var/build'
      - '/var/build/node_modules'

volumes:
  db_data: